name: infwallet
description: An opensource wallet.


version: 1.0.2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  datetime_picker_formfield: ^1.0.0
  flutter_colorpicker: ^0.3.0
  sqflite: ^1.3.0
  path_provider: ^1.6.24
  # permission_handler: ^5.0.1+1
  shared_preferences: ^0.5.12
  flutter_i18n: ^0.15.0
  devicelocale: ^0.3.3
  flutter_file_dialog: ^1.0.0
  file_picker: ^2.1.0
  flutter_echarts: ^1.5.0  

dev_dependencies:
  flutter_launcher_icons: ^0.8.1
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/i18n/


flutter_icons:
  image_path: "icon/icon.png"
  android: true
  ios: false
